window.MutinyPacks = window.MutinyPacks || [];

window.MutinyPacks.push({
  id: 'base',
  name: 'Base Pack',
  description: '100+ standard Mutiny cards.',
  cards: [
    { text: "Wall Touch: {player}, everyone must touch a wall. The last person to do so drinks.", tags: ['social', 'physical'] },
    { text: "2 Truths 1 Lie: {player}, tell everyone two truths and one lie. Everyone who guesses wrong drinks.", tags: ['social', 'memory'] },
    { text: "Mountain: {player}, do an action to {left}. They must repeat it and add one to the player on their left. Continue {direction} until someone fails. Loser drinks.", tags: ['duel', 'physical', 'memory'] },
    { text: "Most Likely: {player}, state a 'who is most likely to...' situation. On the count of three, everyone points. The player with the most points drinks.", tags: ['social'] },
    { text: "Cheers! {player}, lead the group: everyone raise their drinks and say cheers.", tags: ['social'] },
    { text: "Asian Countries: {player}, start naming countries in Asia {direction}. The first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "Dynamic Duo: {player}, if your best friend is playing, you both drink.", tags: ['social'] },
    { text: "Statue: {player}, stay completely still like a statue for one round or drink.", tags: ['physical'] },
    { text: "Elder Statesman: {player}, the oldest player drinks.", tags: ['callout'] },
    { text: "Gents: {player}, all male players drink.", tags: ['callout'] },
    { text: "Sample: {player}, pick another player's drink and take a drink from it.", tags: ['social', 'physical'] },
    { text: "Mexican Wave: {player}, take a drink. Then {left} drinks, continuing {direction} until the wave returns to you.", tags: ['social', 'physical'] },
    { text: "Gestures: {player}, make a gesture. {left} must repeat it and add one. Continue {direction} until someone fails. Loser drinks.", tags: ['duel', 'memory', 'physical'] },
    { text: "Big Foot: {player}, the person with the biggest shoe size must drink.", tags: ['callout'] },
    { text: "World Traveler: {player}, whoever has travelled to the most countries must drink.", tags: ['callout'] },
    { text: "Trivia: {player}, ask {right} a general knowledge question. If they are correct you drink, if they are wrong they drink.", tags: ['duel'] },
    { text: "Car Brands: {player}, start naming car brands {direction}. The first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "Eye Contact Roulette: {player}, everyone look at the ground. On the count of three, look up. Anyone making eye contact must drink.", tags: ['social', 'spicy'] },
    { text: "Even age: {player}, if your age is an even number then drink.", tags: ['callout'] },
    { text: "Flamingo: {player}, everyone stand on one leg. the first person to fall must drink.", tags: ['social', 'physical'] },
    { text: "Longest hair: {player}, the player with the longest hair must drink.", tags: ['callout'] },
    { text: "Fruit: {player}, start naming fruits {direction}. the first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "Gift giver: {player}, {right} must find something and bring it to you as a gift.", tags: ['duel'] },
    { text: "Seeing double: {player}, everyone must drink double for one round.", tags: ['social'] },
    { text: "Guess the number: {player}, think of a number from 1 to 10. the other players guess {direction}. the first person to get it right chooses someone to drink.", tags: ['social'] },
    { text: "Joker: {player}, tell a joke. if no one laughs, you must drink.", tags: ['social'] },
    { text: "Beards: {player}, all bearded players drink.", tags: ['callout'] },
    { text: "Secret drink: {player}, close your eyes while {left} prepares a secret drink. correct guess = they drink, wrong guess = you drink.", tags: ['duel'] },
    { text: "Passport Check: {player}, take a drink for every country you have visited.", tags: ['physical'] },
    { text: "Silenced: {player}, you must not speak English for one round. If you fail, drink.", tags: ['physical'] },
    { text: "Round Robin: {player}, take a drink from every other player's glass.", tags: ['physical'] },
    { text: "Quick Reflexes: {player}, everyone stand up. The last person standing must drink.", tags: ['social', 'physical'] },
    { text: "Floor is Lava: {player}, everyone must touch the floor. The last person to do so must drink.", tags: ['social', 'physical'] },
    { text: "Fists of Five: {player}, on the count of three, all players must show a number from 1 to 5 on their hand. Any players with the same number must drink.", tags: ['social'] },
    { text: "Nicest Eyes: {player}, choose which player has the nicest eyes; they must drink.", tags: ['spicy'] },
    { text: "The Mixologist: {player}, take some of the drink from {right} and pour it into your glass.", tags: ['duel'] },
    { text: "Bottoms Up: {player}, exactly what it says—down your drink.", tags: ['physical'] },
    { text: "Double down: {player}, take two drinks.", tags: ['physical'] },
    { text: "Sample: {player}, everyone offers you their drink. pick one and take a sip.", tags: ['social'] },
    { text: "Southpaw: {player}, use only your left hand for one round or drink.", tags: ['physical'] },
    { text: "Dob: {player}, guess the date of birth of {next}. if you are correct they drink, if you are wrong you drink.", tags: ['duel'] },
    { text: "Lipstick: {player}, anyone wearing lipstick must drink and kiss someone on the cheek.", tags: ['callout', 'spicy'] },
    { text: "Selfie: {player}, take a selfie with {right}. both drink.", tags: ['duel'] },
    { text: "Natural disasters: {player}, start naming natural disasters {direction}. the first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "Best dressed: {player}, choose the player you think is best dressed; they must drink.", tags: ['callout', 'spicy'] },
    { text: "Going to the Bar: {player}, start by naming an alcoholic beverage. Each player adds to the list {direction}. The first to forget or repeat one drinks.", tags: ['social', 'memory'] },
    { text: "Look Left: {player}, the player on your left must drink.", tags: ['duel'] },
    { text: "Flexibility Test: {player}, touch your toes without bending your legs or take a drink.", tags: ['physical'] },
    { text: "Social: Everyone drinks!", tags: ['social'] },
    { text: "Clean Tongue: {player}, you must not swear for three rounds. Every time you swear, you must take a drink.", tags: ['physical'] },
    { text: "Phone Check: {player}, anyone on their phone right now must drink.", tags: ['callout'] },
    { text: "Phone Ban: {player}, for one round, if anyone checks their phone, they must drink.", tags: ['physical'] },
    { text: "Compliments: {player}, start going around {direction} giving each other compliments.", tags: ['social', 'spicy'] },
    { text: "Big Hands: {player}, the person with the biggest hands must take a drink.", tags: ['callout'] },
    { text: "Seven: {player}, count up from 1 {direction}. No player can say a multiple of 7 or a number with a 7; they must say 'drink' instead. When a player says 'drink', the direction changes. First player to mess up must drink.", tags: ['social', 'memory'] },
    { text: "Hands Up: {player}, everyone put their hands in the air. The last to do so must drink.", tags: ['social', 'physical'] },
    { text: "Ladies Night: {player}, all female players must drink.", tags: ['callout'] },
    { text: "Raise Your Glass: {player}, the last person to raise their drink must take a drink.", tags: ['social'] },
    { text: "European Countries: {player}, start naming countries in Europe {direction}. The first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "Sky Scraper: {player}, the tallest player must stand up for one round.", tags: ['callout', 'physical'] },
    { text: "Rock Paper Scissors: {player}, play against {left}. Loser drinks.", tags: ['duel'] },
    { text: "Old Friends: {player}, the player you have known the longest must drink.", tags: ['callout'] },
    { text: "Banned Word: {player}, pick a word that is banned for two rounds. If anyone says this word, they must drink.", tags: ['social'] },
    { text: "Animal Farm: {player}, every player must make an animal noise and then take a drink.", tags: ['social'] },
    { text: "Capital Cities: {player}, go round {direction} naming capital cities. The first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "Currencies: {player}, go round {direction} naming different currencies. The first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "Smell Test: {player}, you must smell every player. The best smelling player must drink.", tags: ['social', 'spicy'] },
    { text: "One Leg: {player}, stand on one leg and take a drink.", tags: ['physical'] },
    { text: "Staring Contest: {player}, have a staring competition with the person in front of you. The loser must drink.", tags: ['duel'] },
    { text: "Shoulder Tap: {player}, turn away. {random} taps your shoulder. If you guess correctly, everyone else drinks. If you are wrong, you drink.", tags: ['social'] },
    { text: "Favourite Colour: {player}, everyone say their favourite colour. Any players that say the same colour must drink.", tags: ['social'] },
    { text: "Push Ups: {player}, do 10 push ups or take a drink.", tags: ['physical'] },
    { text: "Buddy: {player}, pick a player to drink with you.", tags: ['physical'] },
    { text: "The Floor is Lava: {player}, for one round, anyone who touches the floor must drink.", tags: ['social', 'physical'] },
    { text: "US Presidents: {player}, start naming US Presidents {direction}. The first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "Pass the Glass: {player}, everyone pass your drink to {left}. Take a drink from the glass you are now holding.", tags: ['social'] },
    { text: "Triple Threat: {player}, take three drinks.", tags: ['physical'] },
    { text: "US States: {player}, start naming US States {direction}. The first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "The Invisible Man: {player}, everyone must ignore you for one round.", tags: ['social'] },
    { text: "The Diplomat: {player}, you must shake hands with every player.", tags: ['social', 'callout'] },
    { text: "Silent Treatment: {player}, stay silent for one round or take a drink.", tags: ['physical'] },
    { text: "Look Ma, No Hands! {player}, take a drink without using your hands.", tags: ['physical'] },
    { text: "Three Adjectives: {player}, pick three adjectives to describe {left} and then both drink.", tags: ['duel', 'spicy'] },
    { text: "Truth or Lie: {player}, say a statement about yourself. The other players must decide if it is a truth or a lie. If they are wrong they drink, if they are correct you drink.", tags: ['social'] },
    { text: "Double Trouble: {player}, you must drink double for one round.", tags: ['physical'] },
    { text: "Rule Maker: {player}, create a rule that players must follow or drink.", tags: ['social'] },
    { text: "Spin the Bottle: {player}, spin a bottle. Whoever it lands on must drink.", tags: ['social', 'physical'] },
    { text: "The Finger: {player}, everyone point at a player. The person with the most fingers pointed at them must drink.", tags: ['social'] },
    { text: "Thumb War: {player}, have a thumb war with {random}. The loser must finish their drink.", tags: ['duel', 'physical'] },
    { text: "High Five: {player}, high five {right}. Both drink.", tags: ['duel', 'physical'] },
    { text: "Triple Threat: {player}, pick three players to take a drink.", tags: ['social'] },
    { text: "Bottoms Up: {player}, tilt your head all the way back and take a drink.", tags: ['physical'] },
    { text: "Race: {player}, race {random} to finish your drink. The loser takes another drink.", tags: ['duel', 'physical'] },
    { text: "Name Length: {player}, take a drink for every letter in your name.", tags: ['physical'] },
    { text: "Hugs: {player}, give any player a hug.", tags: ['social', 'spicy'] },
    { text: "Sobriety Test: {player}, try to walk in a straight line or take a drink.", tags: ['physical'] },
    { text: "Movie Genres: {player}, start naming movie genres {direction}. The first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "Dog Breeds: {player}, start naming dog breeds {direction}. The first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "Beatles Songs: {player}, start naming Beatles songs {direction}. The first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "Coin Flip: {player}, call heads or tails and flip a coin. If you are correct everyone else drinks; if you are wrong, you drink.", tags: ['social'] },
    { text: "Drink Twins: {player}, all players with the same drink as you must take a drink.", tags: ['social'] },
    { text: "Gender Majority: {player}, if there are more females, all female players drink. If there are more males, all male players drink.", tags: ['callout'] },
    { text: "Rhyme: {player}, say a word. go {direction} rhyming with it. first to fail drinks.", tags: ['social', 'memory'] },
    { text: "Categories: {player}, pick a category. go {direction} naming items. first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "Waterfall: {player}, start drinking. everyone follows. you cannot stop until the previous person stops.", tags: ['social', 'physical'] },
  ]
});
