window.MutinyPacks = window.MutinyPacks || [];
// its not really 100 new cards
window.MutinyPacks.push({
  id: 'exp1',
  name: 'Expansion Pack 1',
  description: '100 new cards!',
  cards: [
    { text: "Battery check: {player}, whoever has the lowest phone battery drinks.", tags: ['callout'] },
    { text: "Red flag: {player}, name a dating red flag. anyone who agrees drinks.", tags: ['social', 'spicy'] },
    { text: "Bad texter: {player}, who is the worst at replying to messages? they drink.", tags: ['social', 'callout'] },
    { text: "Main character: {player}, who in the group has 'main character syndrome'? they take two drinks.", tags: ['callout', 'spicy'] },
    { text: "Ego check: {player}, who would be the first to die in a horror movie? they drink.", tags: ['social', 'callout'] },
    { text: "Follower check: {player}, whoever has the most instagram followers drinks.", tags: ['callout'] },
    { text: "Hot seat: {player}, you have one minute to answer questions from the group. if you skip a question, you drink.", tags: ['social', 'spicy'] },
    { text: "Sibling check: {player}, whoever has the most siblings drinks.", tags: ['callout'] },
    { text: "Tattoo count: {player}, take a drink for every tattoo you have.", tags: ['callout'] },
    { text: "Piercing count: {player}, take a drink for every piercing you have.", tags: ['callout'] },
    { text: "The mimic: {player}, for the next round, you must copy everything {left} does. if you fail, drink.", tags: ['physical'] },
    { text: "Pokemon: {player}, start naming pokemon {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "Pizza toppings: {player}, start naming pizza toppings {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "Streaming: {player}, start naming streaming services {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "Youngest: {player}, the youngest player drinks.", tags: ['callout'] },
    { text: "Commute: {player}, whoever traveled the furthest to get here today drinks.", tags: ['callout'] },
    { text: "Last arrival: {player}, the last person to arrive drinks.", tags: ['callout'] },
    { text: "First arrival: {player}, the first person to arrive drinks.", tags: ['callout'] },
    { text: "Jewelry check: {player}, take a drink for every piece of jewelry you are currently wearing.", tags: ['callout'] },
    { text: "Billionaire: {player}, on the count of three, point at the person most likely to become a billionaire. they drink.", tags: ['social'] },
    { text: "Cult leader: {player}, on the count of three, point at the person most likely to accidentally join a cult. they drink.", tags: ['social'] },
    { text: "Rebound: {player}, whoever was the last person to go through a breakup drinks.", tags: ['social', 'spicy'] },
    { text: "Soft drinks: {player}, start naming soda brands {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "Superheroes: {player}, start naming marvel or dc characters {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "School subjects: {player}, start naming school subjects {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "Sitcoms: {player}, start naming tv sitcoms {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "Chocolate: {player}, start naming chocolate bars {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "Social media: {player}, start naming social media apps {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "Fast food: {player}, start naming fast food chains {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "Colors: {player}, start naming colors {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "Zombie apocalypse: {player}, who in the room would survive the longest in a zombie apocalypse? everyone else drinks.", tags: ['social'] },
    { text: "Grandma: {player}, who is the 'grandma' or 'grandpa' of the group? they drink.", tags: ['social', 'callout'] },
    { text: "Impulse buy: {player}, who is most likely to buy something they don't need? they drink.", tags: ['social'] },
    { text: "Blue eyes: {player}, all players with blue eyes drink.", tags: ['callout'] },
    { text: "Denim check: {player}, everyone wearing denim drinks.", tags: ['callout'] },
    { text: "Socks check: {player}, anyone not wearing socks drinks.", tags: ['callout'] },
    { text: "Watch check: {player}, anyone wearing an analog (non-smart) watch drinks.", tags: ['callout'] },
    { text: "Cartoons: {player}, start naming 90s or 00s cartoons {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "Bands: {player}, start naming rock bands {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "No names: {player}, for one round, anyone who says another player's name must drink.", tags: ['social'] },
    { text: "Southpaw: {player}, everyone must use their non-dominant hand to drink for two rounds.", tags: ['physical'] },
    { text: "Freeze: {player}, at any point in the next 10 minutes, you can freeze. everyone else must freeze too. last to do so drinks.", tags: ['social', 'physical'] },
    { text: "Breakfast club: {player}, anyone who skipped breakfast today drinks.", tags: ['callout'] },
    { text: "Broken bones: {player}, take a drink for every bone you have ever broken.", tags: ['callout'] },
    { text: "Height check: {player}, the shortest player drinks.", tags: ['callout'] },
    { text: "Shoe size: {player}, whoever has the smallest shoe size drinks.", tags: ['callout'] },
    { text: "Sneaker head: {player}, whoever is wearing the most colorful shoes drinks.", tags: ['social', 'callout'] },
    { text: "Black clothing: {player}, everyone wearing black drinks.", tags: ['callout'] },
    { text: "Cracked screen: {player}, anyone with a cracked phone screen drinks.", tags: ['callout'] },
    { text: "Public transport: {player}, anyone who took a bus or train to get here drinks.", tags: ['callout'] },
    { text: "Reunion: {player}, the person you have known for the shortest amount of time drinks.", tags: ['callout'] },
    { text: "Statues: {player}, everyone must freeze. the first person to move drinks.", tags: ['social', 'physical'] },
    { text: "Single life: {player}, everyone who is currently single drinks.", tags: ['callout', 'spicy'] },
    { text: "Taken: {player}, everyone in a relationship drinks.", tags: ['callout', 'spicy'] },
    { text: "Ghosted: {player}, if you have ghosted someone in the last year, take a drink.", tags: ['callout', 'spicy'] },
    { text: "Skinny dipping: {player}, anyone who has gone skinny dipping drinks.", tags: ['callout', 'spicy'] },
    { text: "Last kiss: {player}, whoever had their last kiss the longest ago drinks.", tags: ['callout', 'spicy'] },
    { text: "Best hair: {player}, who has the best hair in the room? they drink.", tags: ['social', 'spicy'] },
    { text: "Dating apps: {player}, start naming dating apps {direction}. first to fail or repeat drinks.", tags: ['social', 'memory', 'spicy'] },
    { text: "Hair dye: {player}, if you have ever dyed your hair a bright color, take a drink.", tags: ['callout'] },
    { text: "Energy drinks: {player}, start naming energy drink brands {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "The Echo: {player}, for one round, you must repeat the last word of every sentence you say. fail = drink.", tags: ['physical'] },
    { text: "Word Association: {player}, pick a word. go around the circle and say the first word that comes to mind {direction}. last to respond drinks.", tags: ['social', 'memory'] },
    { text: "The liar: {player}, who is the best liar in the room? they take a drink.", tags: ['social', 'spicy'] },
    { text: "The ghost: {player}, who is most likely to leave a party without saying goodbye? they drink.", tags: ['social', 'spicy'] },
    { text: "The gossip: {player}, who is the biggest gossip in the group? they drink.", tags: ['social', 'spicy'] },
    { text: "The mess: {player}, who is the 'chaos friend' of the group? they take two drinks.", tags: ['social', 'spicy'] },
    { text: "The picky eater: {player}, who is the hardest person to find a restaurant for? they drink.", tags: ['social', 'spicy'] },
    { text: "Freestyle: {player} rap aslong as you can. Everyone drinks until you stutter, pause or stop.", tags: ['social'] },
    { text: "Plant parent: {player}, anyone who owns a houseplant drinks. take an extra drink if you have killed a plant this year.", tags: ['callout'] },
    { text: "Driving years: {player}, whoever has had their driver's license the longest drinks.", tags: ['callout'] },
    { text: "Brown eyes: {player}, everyone with brown eyes drinks.", tags: ['callout'] },
    { text: "Movie sleeper: {player}, who is most likely to fall asleep in a movie theater? they drink.", tags: ['social'] },
    { text: "Green eyes: {player}, anyone with green or hazel eyes drinks.", tags: ['callout'] },
    { text: "Phone case: {player}, anyone with a clear phone case drinks.", tags: ['callout'] },
    { text: "Middle names: {player}, anyone with more than one middle name drinks.", tags: ['callout'] },
    { text: "Short hair: {player}, the person with the shortest hair in the room drinks.", tags: ['callout'] },
    { text: "Beers: {player}, start naming beers. go {direction} first to repeat or fail drinks.", tags: ['memory'] },
    { text: "Sandwhiches: {player}, start naming sandwhiches. go {direction} first to repeat or fail drinks.", tags: ['memory'] },
    { text: "Spreads on toast: {player}, start naming spreads on toast. go {direction} first to repeat or fail drinks.", tags: ['memory'] },
    { text: "Books vs kindle: {player}, group vote: physical books or e-readers? minority drinks.", tags: ['social'] },
    { text: "Word ender: {player}, for the next round, you must end every sentence with 'aye aye captain'. fail = drink.", tags: ['physical'] },
    { text: "Pinky out: {player}, for the next round you must drink with your pinky extended. fail = drink.", tags: ['physical'] },
    { text: "Whistle: {player}, anyone who can't whistle drinks.", tags: ['callout'] },
    { text: "Ocean animals: {player}, start naming creatures that live in the ocean {direction}. first to fail or repeat drinks.", tags: ['social', 'memory'] },
    { text: "The bow: {player}, you must bow to the group every time you are told to drink for the next round. fail = drink extra.", tags: ['physical'] },
  ]
});