window.MutinyPacks = window.MutinyPacks || [];
// its not really 100 new cards
window.MutinyPacks.push({
  id: 'exp2',
  name: 'Expansion Pack 2',
  description: 'Pirate & fantasy themed cards!',
  cards: [
    { text: "dwarves vs dragon: {player}, countdown to a split vote. 1 hand to have an army of 1,000 loyal dwarves who do whatever you command. 2 hands to own a small car-sized dragon that can fly you around and breathe fire. minority drinks (everyone drinks on a tie).", tags: ['social'] },
    { text: "elf vs dwarf: {player}, countdown to a split vote. 1 hand to live 1,000 years as an elegant elf but you can never drink alcohol. 2 hands to live 100 years as a rugged dwarf but you are permanently tipsy. majority drinks (everyone drinks on a tie).", tags: ['social'] },
    { text: "sorting hat: {player}, start naming harry potter characters {direction}. first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "fellowship: {player}, start naming lord of the rings characters {direction}. first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "tabletop: {player}, start naming board games {direction}. first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "speedrun: {player}, name 5 marvel movies in 10 seconds. if you succeed everyone else drinks, if you fail you drink.", tags: ['social'] },
    { text: "smash bros: {player}, start naming nintendo characters {direction}. first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "minecraft: {player}, start naming minecraft blocks or items {direction}. first to repeat or fail drinks.", tags: ['social', 'memory'] },
    { text: "grandmaster: {player}, name all 6 chess pieces in 5 seconds. if you succeed everyone else drinks, if you fail you drink.", tags: ['social'] },
    { text: "man overboard: {player}, yell 'man overboard!' and hit the deck. the last person to touch the floor drinks. Can be played once at any time", tags: ['social', 'physical'] },
    { text: "scurvy check: {player}, anyone who hasn't drank a glass of water or eaten fruit today drinks.", tags: ['callout'] },
    { text: "abandon ship: {player}, everyone must stand up and find a new seat. the last person to sit down drinks.", tags: ['social', 'physical'] },
    { text: "sea shanty: {player}, slam your drink on the table. everyone must instantly follow. the last person to slam their drink drinks.", tags: ['social', 'physical'] },
    { text: "rum shortage: {player}, everyone hold up your glasses. whoever has the lowest amount of drink left must down it.", tags: ['social', 'callout'] },
    { text: "land ho!: {player}, point at the ceiling. the last person to point drinks.", tags: ['social', 'physical'] },
    { text: "drunken sailor: {player}, countdown from 3. on zero, everyone points at the person who gets chaotic the fastest when drinking. they drink.", tags: ['social'] },
    { text: "fool's gold: {player}, countdown from 3. everyone point at the person who spends money the fastest on a night out. they drink.", tags: ['social'] },
    { text: "abandoning the crew: {player}, countdown from 3. everyone point at the person most likely to sneak home first tonight without saying goodbye. they drink.", tags: ['social'] },
    { text: "mixed signals: {player}, everyone drinking something with a mixer takes a drink.", tags: ['callout'] },
    { text: "pirate salute: {player}, yell 'aye aye captain!'. the last person to stand up and salute drinks.", tags: ['social', 'physical'] },
    { text: "grog spilled: {player}, countdown from 3. everyone point at the person most likely to spill their drink tonight. they drink.", tags: ['social'] },
    { text: "straight grog: {player}, everyone drinking beer, cider, or a straight shot right now takes a drink.", tags: ['callout'] },
    { text: "ice bucket: {player}, anyone with ice cubes in their drink right now must take a drink.", tags: ['callout'] },
    { text: "canned grog: {player}, anyone drinking directly from a can right now takes a drink.", tags: ['callout'] },
    { text: "slow sip: {player}, countdown from 3. everyone point at the slowest drinker in the group. they drink.", tags: ['social'] },
    { text: "low tide: {player}, anyone whose glass is more than half empty right now must take two drinks.", tags: ['callout'] },
    { text: "early starter: {player}, countdown from 3. everyone point at the person most likely to start drinking earliest. they drink.", tags: ['social'] },
    { text: "heavy eyelids: {player}, countdown from 3. everyone point at the person most likely to say 'i'm tired' first tonight. they drink.", tags: ['social'] },
    { text: "fast tide: {player}, countdown from 3. everyone point at the person who finishes their drinks the fastest. they take two drinks.", tags: ['social'] },
    { text: "cheap grog: {player}, whoever bought the cheapest drink takes a drink.", tags: ['callout'] },
    { text: "tall sails: {player}, anyone drinking out of a pint glass or tall glass right now takes a drink.", tags: ['callout'] },
    { text: "local tavern: {player}, whoever lives closest to where you are playing right now takes a drink.", tags: ['callout'] },
    { text: "double grog: {player}, if you already have a backup drink or your next can sitting on the table, take a drink.", tags: ['callout'] },
    { text: "loudest sailor: {player}, countdown from 3. everyone point at the person who speaks the loudest when they get tipsy. they drink.", tags: ['social'] },
    { text: "captain's plan: {player}, countdown from 3. everyone point at the person who organized or convinced everyone to meet up tonight. they drink.", tags: ['social'] },
    { text: "rations check: {player}, anyone who is currently eating a snack or brought food to the table takes a drink.", tags: ['callout'] },
  ]
});